### ISSUE TITLE
Not able to run test which are using kafka.

### ISSUE THREAD

**Issue by ajak6** [intel-hadoop/storm-benchmark#26]
I gett the following error when I try to run tTridentWordCOunt or any other test which use kafka.

Caused by: java.lang.RuntimeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /brokers/topics/fileread/partitions
	at storm.kafka.DynamicBrokersReader.getNumPartitions(DynamicBrokersReader.java:94) ~[stormjar.jar:?]
	at storm.kafka.DynamicBrokersReader.getBrokerInfo(DynamicBrokersReader.java:65) ~[stormjar.jar:?]
	... 12 more
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /brokers/topics/fileread/partitions
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:111) ~[zookeeper-3.4.6.2.4.0.0-169.jar:3.4.6-169--1]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[zookeeper-3.4.6.2.4.0.0-169.jar:3.4.6-169--1]
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1590) ~[zookeeper-3.4.6.2.4.0.0-169.jar:3.4.6-169--1]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:214) ~[stormjar.jar:?]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:203) ~[stormjar.jar:?]
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107) ~[stormjar.jar:?]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.pathInForeground(GetChildrenBuilderImpl.java:199) ~[stormjar.jar:?]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:191) ~[stormjar.jar:?]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:38) ~[stormjar.jar:?]
	at storm.kafka.DynamicBrokersReader.getNumPartitions(DynamicBrokersReader.java:91) ~[stormjar.jar:?]
	at storm.kafka.DynamicBrokersReader.getBrokerInfo(DynamicBrokersReader.java:65) ~[stormjar.jar:?]
	... 12 more
2016-03-30 21:21:48.348 b.s.util [ERROR] Halting process: ("Worker died")
java.lang.RuntimeException: ("Worker died")
	at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:332) [storm-core-0.10.0.2.4.0.0-169.jar:0.10.0.2.4.0.0-169]
	at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.6.0.jar:?]
	at backtype.storm.daemon.worker$fn__7818$fn__7819.invoke(worker.clj:636) [storm-core-0.10.0.2.4.0.0-169.jar:0.10.0.2.4.0.0-169]
	at backtype.storm.daemon.executor$mk_executor_data$fn__7078$fn__7079.invoke(executor.clj:256) [storm-core-0.10.0.2.4.0.0-169.jar:0.10.0.2.4.0.0-169]
	at backtype.storm.util$async_loop$fn__544.invoke(util.clj:485) [storm-core-0.10.0.2.4.0.0-169.jar:0.10.0.2.4.0.0-169]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.6.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
2016-03-30 21:21:48.348 b.s.util [ERROR] Halting process: ("Worker died")
java.lang.RuntimeException: ("Worker died")
	at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:332) [storm-core-0.10.0.2.4.0.0-169.jar:0.10.0.2.4.0.0-169]
	at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.6.0.jar:?]
	at backtype.storm.daemon.worker$fn__7818$fn__7819.invoke(worker.clj:636) [storm-core-0.10.0.2.4.0.0-169.jar:0.10.0.2.4.0.0-169]
	at backtype.storm.daemon.executor$mk_executor_data$fn__7078$fn__7079.invoke(executor.clj:256) [storm-core-0.10.0.2.4.0.0-169.jar:0.10.0.2.4.0.0-169]
	at backtype.storm.util$async_loop$fn__544.invoke(util.clj:485) [storm-core-0.10.0.2.4.0.0-169.jar:0.10.0.2.4.0.0-169]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.6.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

Any idea what should I do, I tried giving broker list like hostname1:2181,hostname2:2181 and also a single broker.. didnt helped. Any help on this.

broker.list: "broker:9092"
zookeeper.servers: "zookeeperServer:2181/kafka"
kafka.root.path: "/usr/hdp/current/kafka-broker"
topic: "fileread"
client_id: "trident"

# topology configurations
topology.workers: 4
topology.acker.executors: 4
topology.max.spout.pending: 200
topology.name: "TridentWordCount1"

**Comment by manuzhang** [comment]
Please check whether the topic exist at the path  `zookeeper.servers + kafka.root.path` like

```
bin/kafka-topics --list --zookeeper ${zookeeper.servers + kafka.root.path}
```
